# Global settings
num_workers: 4
cuda: True
global_seed: 42
base_patch_size: [256, 256]
model_stride: [64, 64]

# Data settings
train_dataset: /data/ssd/liuchaolei/image_datasets/DFCLIC
hdf5_dataset: /data/ssd/liuchaolei/image_datasets/scdata.hdf5
test_dataset: /data/ssd/liuchaolei/image_datasets/Kodak24/HR