# Example configuration; set paths and training bounds for your checkpoint.
enable_xformers_memory_efficient_attention: false
color_fix: false
model:
  mode: test
  sd_path: weights/sd-turbo
  elic_path: weights/elic_official.pth
  resume_train: false
  codec_path: weights/baseline_4ch.pth.tar
  lora_rank_unet: 32
  lora_rank_vae: 16
  vae_decoder_tiled_size: 160
  vae_encoder_tiled_size: 1024
  latent_tiled_size: 96
  latent_tiled_overlap: 32
  pos_prompt: A high-resolution, 8K, ultra-realistic image with sharp focus, vibrant
    colors, and natural lighting.
  freeze_aux_encoder: true
  latent_channels: 4
  timesteps: 999
rec_path: results/baseline_4ch
use_ema: false
lmbda: 2.0
