# Learning / optimizer
num_train_epochs: 4000
max_train_steps: 400000
lr_warmup_steps: 500
lr_scheduler: constant # ["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]

scale_lr: False
learning_rate: !!float 5e-5
aux_learning_rate: !!float 1e-5
clip_max_norm: 1.0
adam_weight_decay: !!float 1e-2
adam_epsilon: !!float 1e-8
lr_num_cycles: 1
lr_power: 0.1
set_grads_to_none: True

mixed_precision: 'no'
report_to: wandb
gradient_checkpointing: False
allow_tf32: False
enable_xformers_memory_efficient_attention: False


# Loss
clip_model_path: /data/ssd/liuchaolei/models/Others/clip-vit-base-patch32
lmbda: 2.0 ########################################################################
mse_coefficient: 2
lpips_coefficient: 1.0
clip_coefficient: 0.1
gan_coefficient: 0.1


# Logging / checkpoint
save: True
checkpointing_steps: 20000
savepath: /data/ssd/liuchaolei/results/sc/sc-channel ####################################
save_best: False
min_steps_for_best: 50000
only_best: False
log_every: 100


# Training control
global_batch_size: 8
gradient_accumulation_steps: 8
patch_size: [512, 512]
precision: none  # bf16 / fp16 / none
compile: False ########################################################################
wandb: False
save_ema: False
ema_update_every: 5
gamma: 0.001
ema_position: cpu  # cpu / gpu


# StableCodec Model
model:
  lambda_min: 0.5
  lambda_max: 32.0
  lambda_ref: 1.0   # 验证和 criterion 的参考 λ
  sd_path: /data/ssd/liuchaolei/models/Diffusion/sd-turbo ########################################################################
  elic_path: /data/ssd/liuchaolei/models/Image-Coder/StableCodec/checkpoints/elic_official.pth
  dcae_path: /data/ssd/liuchaolei/models/Image-Coder/DCAE/0.0018checkpoint_best.pth.tar
  # Pretrain / resume
  resume_train: False ########################################################################
  codec_path: /data/ssd/liuchaolei/results/sc/sc-channel/stage1/channel4/checkpoints/checkpoint-120000.pth.tar ########################################################################

  # Details about the model architecture
  lora_rank_unet: 32
  lora_rank_vae: 16
  vae_decoder_tiled_size: 160
  vae_encoder_tiled_size: 1024
  latent_tiled_size: 96
  latent_tiled_overlap: 32
  pos_prompt: A high-resolution, 8K, ultra-realistic image with sharp focus, vibrant colors, and natural lighting.

  freeze_aux_encoder: True
  latent_channels: 4 ########################################################################
  timesteps: 999 ########################################################################

  # CFT settings
  cft_inject_blocks: [0, 1, 2]
  cft_w: 0.5  # 0=diff支路, 1=res支路


# GAN configs
gan_loss_type: multilevel_sigmoid_s