# Example configuration; set paths and training bounds for your checkpoint.
num_train_epochs: 4000
max_train_steps: 400000
lr_warmup_steps: 500
lr_scheduler: constant
scale_lr: false
learning_rate: 5.0e-05
aux_learning_rate: 1.0e-05
clip_max_norm: 1.0
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
lr_num_cycles: 1
lr_power: 0.1
set_grads_to_none: true
mixed_precision: 'no'
report_to: null
gradient_checkpointing: false
allow_tf32: false
enable_xformers_memory_efficient_attention: false
clip_model_path: openai/clip-vit-base-patch32
lmbda: 2.0
mse_coefficient: 2
lpips_coefficient: 1.0
clip_coefficient: 0.0
gan_coefficient: 0.1
save: true
checkpointing_steps: 20000
savepath: results/training
save_best: false
min_steps_for_best: 50000
only_best: false
log_every: 100
global_batch_size: 8
gradient_accumulation_steps: 8
patch_size:
- 512
- 512
precision: none
compile: false
wandb: false
save_ema: false
ema_update_every: 5
gamma: 0.001
ema_position: cpu
model:
  lambda_min: 0.2
  lambda_max: 128.0
  lambda_ref: 1.0
  sd_path: weights/sd-turbo-256
  elic_path: weights/elic_official.pth
  resume_train: false
  codec_path: weights/stage1.pth.tar
  lora_rank_unet: 32
  lora_rank_vae: 16
  vae_decoder_tiled_size: 160
  vae_encoder_tiled_size: 1024
  latent_tiled_size: 96
  latent_tiled_overlap: 32
  pos_prompt: A high-resolution, 8K, ultra-realistic image with sharp focus, vibrant
    colors, and natural lighting.
  freeze_aux_encoder: true
  latent_channels: 256
  timesteps: 999
gan_loss_type: multilevel_sigmoid_s
