# Example configuration; set paths and training bounds for your checkpoint.
val_batch_size: 4
validation_steps: 100
val_first: false
save_val: false
save_steps: 10000
crop_val: true
enable_xformers_memory_efficient_attention: false
set_grads_to_none: true
world_size: 1
local_rank: -1
dist_url: env://
color_fix: false
